#!/usr/bin/env bash
#
#   archvillainette 2024
#
#      ▄████████ ▀████    ▐████▀    ▄█    █▄       ▄█   ▄█▄ ████████▄ 
#     ███    ███   ███▌   ████▀    ███    ███     ███ ▄███▀ ███   ▀███
#     ███    █▀     ███  ▐███      ███    ███     ███▐██▀   ███    ███
#     ███           ▀███▄███▀     ▄███▄▄▄▄███▄▄  ▄█████▀    ███    ███
#   ▀███████████    ████▀██▄     ▀▀███▀▀▀▀███▀  ▀▀█████▄    ███    ███
#            ███   ▐███  ▀███      ███    ███     ███▐██▄   ███    ███
#      ▄█    ███  ▄███     ███▄    ███    ███     ███ ▀███▄ ███   ▄███
#    ▄████████▀  ████       ███▄   ███    █▀      ███   ▀█▀ ████████▀ 
#                                                 ▀                   
#   Keybind configuration for BSPWM
#

# Disable middle click copy-paste
~button2
    ;echo -n | xclip -in

# Reload BSPWM
super + shift + Escape
	bspc wm -r
	
# Reload Keybindings
super + Escape
	pkill -USR1 -x sxhkd; dunstify -i keyboard "sxhkd" "Keybindings have been reloaded."

# Show keybindings help
alt + F1
	keybindHelp

# Show archwiki
alt + F2
	openApp --archwiki

# Hide/Show Bar
super + h
	hideBar

# Open Terminal
super + Return
	openApp --terminal

# Open Floating Terminal
super + shift + Return
	openApp --floatingterminal

# Application Menu
super + space
	openApp --menu

# Close and kill
super + {_,shift + }q
	bspc node -{c,k}

# Rotate desktop
super + r
	bspc node @/ --rotate {90,-90}

# Circulate the leaves of the tree
super + c
	bspc node @/ --circulate {backward,forward}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# Toggle floating
super + t
    if [ -z "$(bspc query -N -n focused.floating)" ]; then \
        bspc node focused -t floating; \
    else \
        bspc node focused -t tiled; \
    fi

# Toggle fullscreen
super + f
    bspc node focused -t \~fullscreen

# Toggle psuedo
super + s
    bspc node focused -t \~pseudo_tiled

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# Switch workspace
super + {Left,Right}
	bspc desktop -f {prev,next}.local

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}' '--follow'
	
# Send focused Node to workspace directionally
super + shift + {Left,Right}
	bspc node -d {prev,next} '--follow'

# Show Rofi calculator
alt + c
    openApp --calc
	
# Show clipmenu
#alt + v

# Manage brightness
XF86MonBrightness{Up,Down}
    adjustBrightness {up,down}

# Volume control
XF86Audio{RaiseVolume,LowerVolume,Mute}
	adjustVolume{ --inc, --dec, --toggle}

# Screenshot
XF86Launch3
	takeScreenshot

# Screenshot window
XF86Launch3 + super
	takeScreenshot --active

# Delayed screenshot
XF86Launch3 + super + shift
	takeScreenshot --in3

# Toggle touchpad
XF86TouchpadToggle
	toggleTouchpad

# Screenshot selection
super + F6
	takeScreenshot --sel

# Rofi power menu
super + l
	openApp --powermenu

# Pause/play song
super + backslash
	playerctl play-pause

# Previous song
super + bracketright
	playerctl next

# Next song
super + bracketleft
	playerctl previous