#!/usr/bin/env bash
#  ██╗   ██╗ ██████╗ ██╗     ██╗   ██╗███╗   ███╗███████╗
#  ██║   ██║██╔═══██╗██║     ██║   ██║████╗ ████║██╔════╝
#  ██║   ██║██║   ██║██║     ██║   ██║██╔████╔██║█████╗
#  ╚██╗ ██╔╝██║   ██║██║     ██║   ██║██║╚██╔╝██║██╔══╝
#   ╚████╔╝ ╚██████╔╝███████╗╚██████╔╝██║ ╚═╝ ██║███████╗
#    ╚═══╝   ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝
#
#	gh0stzk
#	https://github.com/gh0stzk/dotfiles
#	This script controls the volume of your system, using pamixer.
#	23.09.2023 09:30:24
#

notify_cmd='dunstify -u low -h string:x-dunst-stack-tag:cvolum'
VOLUME_STEPS=5

# Get Volume
get_volume() {
    pamixer --get-volume-human | sed 's/%//'
}

# Get icons
get_icon() {
    current="$(get_volume)"
    if [[ "$current" -eq "0" || "$current" == "muted" ]]; then
        icon="audio-volume-muted"
    else
        icon="audio-volume-high"
    fi
}

# Notify
notify_user() {
    volume=$(get_volume)
    bar=$(seq -s "─" 0 $((volume / 5)) | sed 's/[0-9]//g')
    ${notify_cmd} -i "$icon" "Volume" "$volume%" -h int:value:$(($volume))
}

# Adjust Volume
adjust_volume() {
    [[ $(pamixer --get-mute) == true ]] && pamixer -u
    pamixer --allow-boost --set-limit 150 "$1" "$2" && get_icon && notify_user
}

# Toggle Mute
toggle_mute() {
    if [[ $(pamixer --get-mute) == false ]]; then
        pamixer --toggle-mute
        get_icon
        message="Mute"
    else
        pamixer --toggle-mute
        get_icon
        message="Unmute"
    fi
    ${notify_cmd} -i "$icon" "$message"
}

# Execute accordingly
if command -v pamixer &>/dev/null; then
    case "$1" in
        --get) get_volume ;;
        --inc) adjust_volume -i $VOLUME_STEPS ;;
        --dec) adjust_volume -d $VOLUME_STEPS ;;
        --toggle) toggle_mute ;;
        *) echo "$(get_volume)%" ;;
    esac
else
    ${notify_cmd} "'pamixer' is not installed."
fi
