#!/usr/bin/env bash
#   Original script was written by z0mbi3
#   https://github.com/gh0stzk/dotfiles
#   20.12.2023 16:10:25
#   This version is modified for personal use by archvillainette.

timestamp=$(date +%Y-%m-%d-%H%M%S)
filename="$SCREENSHOTS/screenshot-${timestamp}.png"

if [ ! -d "${SCREENSHOTS}" ]; then
    mkdir -p "${SCREENSHOTS}"
fi

show_notification() {
    if [[ -e "$filename" ]]; then
        dunstify --replace=699 -i "$filename" "Screenshot" "Screenshot saved and copied to clipboard."
    else
        dunstify --replace=699 -i trashindicator "Screenshot" "Screenshot cancelled."
    fi
}

take_screenshot() {
    maim -u "$@" "$filename"
    xclip -selection clipboard -t image/png -i "$filename"
    show_notification
}

countdown() {
    for sec in $(seq "$1" -1 1); do
        dunstify -t 750 --replace=699 -i time "Taking shot in : $sec"
        sleep 1
    done
}

case $1 in
    --in10)
        countdown 10 && take_screenshot ;;
    --in3)
        countdown 3 && take_screenshot ;;
    --sel)
        take_screenshot -s -o ;;
    --active)
        take_screenshot -i "$(xdotool getactivewindow)" ;;
    *)
        take_screenshot ;;
esac
